### ISSUE TITLE
Singular / Plural form of units

### ISSUE THREAD

**Issue by LostKobrakai** [kipcole9/cldr_units#7]
It seems like `Cldr.Unit.to_string` is always returning the plural form of the units name.

Edit: Seems like it's working for "en" as locale, but not for "de".

**Comment by kipcole9** [comment]
Thanks for the report.  The issue came down to the incorrect usage of pluralisation rules (Ordinal v Cardinal).  It is now correctly Cardinal.  I added some tests in "de" to verify.

I also observed that the pluralisation data for "de" units may not be complete but as a native German speaker I'm sure you can advise better than I can :-)

Published to hex as version 1.2.1.

**Comment by LostKobrakai** [comment]
Thanks for the quick fix. 

> I also observed that the pluralisation data for "de" units may not be complete but as a native German speaker I'm sure you can advise better than I can :-)

I checked this yesterday for the unit I was using and that one is complete :D
